<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Exercice Routeur MVC</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>

<body>
    <header class="bg-dark text-white p-3">


        <nav class="navbar navbar-dark bg-dark fixed-top">
            <div class="container-fluid">
                <a class="navbar-brand" href="index.php">Gestion des utilisateurs</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasDarkNavbar" aria-labelledby="offcanvasDarkNavbarLabel">
                    <div class="offcanvas-header">
                        <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel">Dark offcanvas</h5>
                        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                    </div>
                    <div class="offcanvas-body">
                        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">

                            <li class="nav-item">
                                <a class="nav-link" href="index.php?route=create_user">Ajouter un utilisateur</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="index.php?route=update_user">Mettre à jour un utilisateur</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" href="index.php?route=show_user">Voir un utilisateur</a>
                            </li>

                        </ul>

                    </div>
                </div>
            </div>
        </nav>
    </header>


    </div>



    <div class="container mt-5">
        <?php


        if ($route === "show_user") {
            require "templates/users/show.phtml";
        } elseif ($route === "update_user") {
            require "templates/users/update.phtml";
        } elseif ($route === "create_user") {
            require "templates/users/create.phtml";
        } else {
            require "templates/users/list.phtml";
        }
        ?>
    </div>





    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"></script>

</body>

</html>