<main class="container mt-5">
    <h1 class="display-4 text-center">La liste des utilisateurs</h1>
    <div class="container mt-5">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">Id</th>
                    <th scope="col">Prénom</th>
                    <th scope="col">Nom</th>
                    <th scope="col">Email</th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
                <?php
                foreach ($users as $user) {
                ?>
                    <tr>
                        <td><?= $user->getId(); ?></td>
                        <td><?= $user->getFirstName(); ?></td>
                        <td><?= $user->getLastName(); ?></td>
                        <td><?= $user->getEmail(); ?></td>
                        <td>
                            <a href="index.php?route=show_user&id=<?= $user->getId(); ?>" class="btn btn-primary btn-sm" title="Voir">
                                <i class="bi bi-eye"></i>
                            </a>
                            <a href="index.php?route=update_user&id=<?= $user->getId(); ?>" class="btn btn-warning btn-sm" title="Modifier">
                                <i class="bi bi-pencil"></i>
                            </a>
                            <a href="index.php?route=delete_user&id=<?= $user->getId(); ?>" class="btn btn-danger btn-sm" title="Supprimer" onclick="return confirm('Êtes-vous sûr de vouloir supprimer cet utilisateur ?');">
                                <i class="bi bi-trash"></i>
                            </a>
                        </td>
                    <?php
                }
                    ?>
            </tbody>







        </table>
    </div>

</main>