<main class="container mt-5">
    <h1 class="display-4 text-center">La liste des utilisateurs</h1>
    <div class="container mt-5">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">Id</th>
                    <th scope="col">Prénom</th>
                    <th scope="col">Nom</th>
                    <th scope="col">Email</th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
                <?php
                foreach ($users as $user) {
                ?>
                    <tr>
                        <td><?= $user->getId(); ?></td>
                        <td><?= $user->getFirstName(); ?></td>
                        <td><?= $user->getLastName(); ?></td>
                        <td><?= $user->getEmail(); ?></td>
                        <td>Actions à définir plus tard</td>
                    <?php
                }
                    ?>
            </tbody>







        </table>
    </div>

</main>